### ISSUE TITLE
Bad URL Issue

### ISSUE THREAD

**Issue by iOSDevSK** [intergalacticalvariable/reader#8]
If the user enters a URL that doesn't work, the entire container crashes.

[Crawler] INFO: Starting scrap for URL: https://opensubtitles.tawk.hep/article/upgrading-to-vip
Starting scrap for URL: https://opensubtitles.tawk.hep/article/upgrading-to-vip
Crawl options: {
  proxyUrl: undefined,
  cookies: [],
  favorScreenshot: false,
  removeSelector: undefined,
  targetSelector: undefined,
  waitForSelector: undefined,
  overrideUserAgent: undefined,
  timeoutMs: undefined,
  withIframe: false
}
Crawler options: CrawlerOptionsHeaderOnly {
  respondWith: 'default',
  withGeneratedAlt: false,
  withLinksSummary: false,
  withImagesSummary: false,
  noCache: false,
  keepImgDataUrl: false,
  withIframe: false,
  removeSelector: undefined,
  targetSelector: undefined,
  waitForSelector: undefined,
  userAgent: undefined,
  proxyUrl: undefined
}
Using default scraping method
Scraping options: {
  proxyUrl: undefined,
  cookies: [],
  favorScreenshot: false,
  removeSelector: undefined,
  targetSelector: undefined,
  waitForSelector: undefined,
  overrideUserAgent: undefined,
  timeoutMs: undefined,
  withIframe: false
}
[CHANGE_LOGGER_NAME] INFO: Page 1: Scraping https://opensubtitles.tawk.hep/article/upgrading-to-vip { url: 'https://opensubtitles.tawk.hep/article/upgrading-to-vip' }
[CHANGE_LOGGER_NAME] INFO: Page 1: Attempting to set cookies: []
/app/node_modules/tld-extract/index.js:43
      throw new Error("Invalid TLD " + JSON.stringify({parts, tld_level, allowUnknownTLD}));
            ^

Error: Invalid TLD {"parts":["opensubtitles","tawk","hep"],"tld_level":-1,"allowUnknownTLD":false}
    at parse_host (/app/node_modules/tld-extract/index.js:43:13)
    at parse_url (/app/node_modules/tld-extract/index.js:9:10)
    at /app/build/services/puppeteer.js:280:57
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:238:32
    at async CdpHTTPRequest.finalizeInterceptions (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/HTTPRequest.js:147:9)

Node.js v18.20.4
Initializing CrawlerHost
CrawlerHost constructor called
Initializing CrawlerHost with dependencies: {
  puppeteerControl: true,
  jsdomControl: true,
  firebaseObjectStorage: true,
  threadLocal: true
}
Server is running on port 3000

**Comment by intergalacticalvariable** [comment]
Thanks for fixing!
